name: SeparatedLootChest
version: '${version}'
main: com.tinyshellzz.separatedLootChest.SeparatedLootChest
api-version: '1.20'
load: POSTWORLD
authors: [ Tinyshellzz ]
folia-supported: true
soft-depend: [PlaceholderAPI]
commands:
  schest:
    description: schest Command.
    usage: /schest ...
    default: true